### PR TITLE
fix: tolerate an undefined `baseUrl` compiler option

### LINKED ISSUE #143: Allow missing baseUrl for TS 4.1+
TypeScript 4.1+ support `paths` without `baseUrl`. See:

- https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/
- microsoft/TypeScript#40101

Effectively, the paths become relative to the `tsconfig.json` file.

I'm testing a project with the new beta and `baseUrl` removed to get better auto-completion, but it appears this library (which is used by tsconfig-paths-webpack-plugin) requires `baseUrl` to be specified. I've even tried in the plugin to override baseUrl with `.` (which is pretty much what TS does), but since the plugin loads the config using this library and this library throws an error, the plugin doesn't get to the point where it could override the config.

Perhaps if the config has no `baseUrl`, it could be treated as a `baseUrl` of `'.'`? Or, change the result to allow undefined locations (and update the plugin)?

2022 EDIT: since it's been a long time and this hasn't been fixed, I had written my own little function to do everything needed for path mapping: https://github.com/microsoft/pyright/blob/169c6089b9914870c43622743c75844657cd9d70/build/lib/webpack.js#L90

### PR DESCRIPTION
**Pull request by aleclarson**
Fixes #143

This is a breaking change.

### CODE REVIEW

File: src/config-loader.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export interface ConfigLoaderParams {
 export interface ConfigLoaderSuccessResult {
   resultType: "success";
   configFileAbsolutePath: string;
-  baseUrl: string;
+  baseUrl?: string;
```
Comment (aleclarson) [inline src/config-loader.ts:25]: This is why it's a breaking change

**Review by marvinroger — APPROVED** [review]

File: src/config-loader.ts (hunk 1 above)
Comment (marvinroger) [reply src/config-loader.ts:25]: Making a previously required property optional is not a breaking change IMO, especially in this case:

* It won't change anything for projects having a `baseUrl`
* There's virtually no projects using `tsconfig-paths` that currently do not have a `baseUrl`, because it was basically broken

Comment (aleclarson) [reply src/config-loader.ts:25]: This PR introduces a compiler error into any downstream package that happens to use `loadConfig` and expects the `baseUrl` property to only ever be a string. If a change can cause downstream compiler errors, I consider it breaking.

Comment (marvinroger) [reply src/config-loader.ts:25]: Oh I was not aware of the public API, my bad!

**Comment by jonaskello** [comment]
@aleclarson Could you also add an entry for this PR in the CHANGELOG under unreleased heading, noting it as a breaking change.

**Comment by aleclarson** [comment]
LGTM
